# Generated by Django 3.1.1 on 2020-11-16 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoker', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='', max_length=200)),
                ('drink_level', models.CharField(choices=[('Abstemious', 'Abstemious'), ('Social Drinker', 'Social Drinker'), ('Casual Drinker', 'Casual Drinker')], default='', max_length=200)),
                ('dress_preference', models.CharField(choices=[('Formal', 'Formal'), ('Informal', 'Informal'), ('No Preference', 'No Preference')], default='', max_length=200)),
                ('ambience', models.CharField(choices=[('Family', 'Family'), ('Friends', 'Friends'), ('Solitary', 'Solitary')], default='', max_length=200)),
                ('transport', models.CharField(choices=[('Car Owner', 'Car Owner'), ('Public', 'Public Transport'), ('On foot', 'On foot')], default='', max_length=200)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widow', 'Widow')], default='', max_length=200)),
                ('children', models.CharField(choices=[('Independent', 'Independent'), ('Dependent', 'Dependent'), ('Kids', 'Kids')], default='', max_length=200)),
                ('interest', models.CharField(choices=[('Technology', 'Technology'), ('Eco-Friendly', 'Eco-Friendly'), ('Retro', 'Retro'), ('Variety', 'Variety'), ('None', 'None')], default='', max_length=200)),
                ('personality', models.CharField(choices=[('hard-worker', 'Hard-worker'), ('hunter-ostentatious', 'Hunter-ostentatious'), ('thrifty-protector', 'Thrifty-protector'), ('conformist', 'Conformist')], default='', max_length=200)),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Jewish', 'Jewish'), ('Muslim', 'Muslim'), ('Mormon', 'Mormon'), ('Other', 'Other'), ('None', 'None')], default='', max_length=200)),
                ('activity', models.CharField(choices=[('Student', 'Student'), ('Professional', 'Professional'), ('Unemployed', 'Unemployed')], default='', max_length=200)),
                ('fav_color', models.CharField(choices=[('red', 'Red'), ('black', 'Black'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('white', 'White'), ('blue', 'Blue'), ('yellow', 'Yellow')], default='', max_length=200)),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(500)])),
                ('budget', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=200)),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.2)])),
                ('age', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
