# Generated by Django 3.1.1 on 2020-11-17 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Charlottesville', 'Charlottesville'), ('NoVA', 'NoVA'), ('Roanoke', 'Roanoke'), ('Richmond', 'Richmond'), ('Virginia Beach', 'Virginia Beach'), ('Blacksburg', 'Blacksburg')], default='', max_length=200)),
                ('smoker', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='', max_length=200)),
                ('drink_level', models.CharField(choices=[('abstemious', 'Abstemious'), ('social drinker', 'Social Drinker'), ('casual drinker', 'Casual Drinker')], default='', max_length=200)),
                ('dress_preference', models.CharField(choices=[('formal', 'Formal'), ('informal', 'Informal'), ('no preference', 'No Preference')], default='', max_length=200)),
                ('ambience', models.CharField(choices=[('family', 'Family'), ('friends', 'Friends'), ('solitary', 'Solitary')], default='', max_length=200)),
                ('transport', models.CharField(choices=[('car owner', 'Car Owner'), ('public', 'Public Transport'), ('on foot', 'On foot')], default='', max_length=200)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widow', 'Widow')], default='', max_length=200)),
                ('children', models.CharField(choices=[('independent', 'Independent'), ('dependent', 'Dependent'), ('kids', 'Kids')], default='', max_length=200)),
                ('interest', models.CharField(choices=[('technology', 'Technology'), ('eco-friendly', 'Eco-Friendly'), ('retro', 'Retro'), ('variety', 'Variety'), ('none', 'None')], default='', max_length=200)),
                ('personality', models.CharField(choices=[('hard-worker', 'Hard Worker'), ('hunter-ostentatious', 'Extrovert'), ('thrifty-protector', 'Introvert'), ('conformist', 'Conformist')], default='', max_length=200)),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Jewish', 'Jewish'), ('Muslim', 'Muslim'), ('Other', 'Other'), ('none', 'None')], default='', max_length=200)),
                ('activity', models.CharField(choices=[('student', 'Student'), ('professional', 'Professional'), ('unemployed', 'Unemployed')], default='', max_length=200)),
                ('fav_color', models.CharField(choices=[('red', 'Red'), ('black', 'Black'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('white', 'White'), ('blue', 'Blue'), ('yellow', 'Yellow')], default='', max_length=200)),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(500)])),
                ('budget', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=200)),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.2)])),
                ('age', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
