# Generated by Django 3.1.1 on 2020-11-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20201116_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattributes',
            name='smoker',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='', max_length=200),
        ),
    ]
