# Generated by Django 3.1.1 on 2020-11-16 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20201116_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattributes',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.2)]),
        ),
    ]
