# Generated by Django 3.1.1 on 2020-11-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_auto_20201116_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattributes',
            name='location',
            field=models.CharField(choices=[('Charlottesville', 'Charlottesville'), ('NoVA', 'NoVA'), ('Roanoke', 'Roanoke'), ('Richmond', 'Richmond'), ('Virginia Beach', 'Virginia Beach'), ('Blacksburg', 'Blacksburg')], default='', max_length=200),
        ),
    ]
