# Generated by Django 3.1.1 on 2020-11-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_userattributes_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattributes',
            name='activity',
            field=models.CharField(choices=[('student', 'Student'), ('professional', 'Professional'), ('unemployed', 'Unemployed')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userattributes',
            name='ambience',
            field=models.CharField(choices=[('family', 'Family'), ('friends', 'Friends'), ('solitary', 'Solitary')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userattributes',
            name='children',
            field=models.CharField(choices=[('independent', 'Independent'), ('dependent', 'Dependent'), ('kids', 'Kids')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userattributes',
            name='dress_preference',
            field=models.CharField(choices=[('formal', 'Formal'), ('informal', 'Informal'), ('no preference', 'No Preference')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userattributes',
            name='drink_level',
            field=models.CharField(choices=[('abstemious', 'Abstemious'), ('social drinker', 'Social Drinker'), ('casual drinker', 'Casual Drinker')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userattributes',
            name='interest',
            field=models.CharField(choices=[('technology', 'Technology'), ('eco-friendly', 'Eco-Friendly'), ('retro', 'Retro'), ('variety', 'Variety'), ('none', 'None')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userattributes',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widow', 'Widow')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userattributes',
            name='personality',
            field=models.CharField(choices=[('hard-worker', 'Hard Worker'), ('hunter-ostentatious', 'Extrovert'), ('thrifty-protector', 'Introvert'), ('conformist', 'Conformist')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userattributes',
            name='religion',
            field=models.CharField(choices=[('Christian', 'Christian'), ('Jewish', 'Jewish'), ('Muslim', 'Muslim'), ('Other', 'Other'), ('none', 'None')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userattributes',
            name='transport',
            field=models.CharField(choices=[('car owner', 'Car Owner'), ('public', 'Public Transport'), ('on foot', 'On foot')], default='', max_length=200),
        ),
    ]
