NOVA_dict = {
    "Mexican": ['https://www.guaposrestaurant.com/location/fair-lakes-guapos-restaurant/ ',
'http://www.elpasomexicanrestaurants.com/ ',
'http://www.coyotegrille.com/ ',
'http://www.anitascorp.com/ ',
'https://www.guajillomexican.com/ ',
'http://www.eltiogrill.com/'
'https://www.facebook.com/pampa.sazone',
],
    "Asian": ['https://hotspotchantilly.wixsite.com/website',
'http://www.districtdumplingsfairfax.com/ ',
'http://www.kogiya.com/',
'http://oegadgib.com/',
'https://sistersthai.com/',
'https://www.facebook.com/pages/Viet-House-Restaurant/117697194916698',
'https://www.facebook.com/Hong-Kong-Pearl-Seafood-Restaurant-261076060610322/',
'https://www.grubhub.com/restaurant/blue-pearl-buffet-6820-commerce-st-springfield/2234586 '],
    "Italian": ['http://www.dolcevitaitaliankitchenandwinebar.com/',
'http://www.pazzopomodoro.com/vienna',
'http://www.trattoriavillagio.com/',
'http://osteriadaninova.com/ ',
'http://www.pomodoropastapizza.com/',
'https://www.altastradarestaurant.com/',
'http://www.cantinaditalia.com/',
],
    "Mediterranean/Middle East": ['https://anatolianbistro.com/',
'http://www.istanbulblue.net/',
'http://www.jerusalem-va.net/',
'http://mazadarrestaurantva.com/',
'http://www.mejanarestaurant.com/ ',
'http://www.flame-kabob.com/ ',
'https://m.facebook.com/bakudelicious/',
],
    "American": ['http://artiesva.com/',
'http://sweetwatertavern.pub/',
'http://21gab.com/',
'http://coastalflats.net/',
'https://americanprimeco.com/outdoor',
'http://mikesamerican.com/ ',
'https://dogfishalehouse.com/dfh-alehouse-fairfax.html',
'https://www.lostdogcafe.com/',
'https://chutzpahdeli.com/',
],
    "Dessert/Cafe": ['http://www.dulcecrepes.com/',
'http://dessertloungeva.site/',
'http://magnoliaofvienna.com/',
'https://www.grubhub.com/restaurant/manoa-bakery-cafe-7326-little-river-turnpike-annandale/2062340',
],
    "Modern": ['http://www.2941.com/ ',
'https://mapleaverestaurant.com/private-events/ ',
'http://bellissimorestaurant.com/',
'http://www.clarityvienna.com/',
],
    "European": ['http://m.bistrolhermitage.com/ ',
'http://theauldshebeenva.com/',
'https://braborestaurant.com/ ',
'http://www.laubergechezfrancois.com/ ',
'https://www.nandosperiperi.com/',
'http://www.ambarrestaurant.com/home-page-clarendon/ ',
'http://www.euro-bistro.com/ ',
'http://balkanrichmond.com/ ',
'http://europeantasterva.com/ ',
'http://www.laubergechezfrancois.com/ ',
'https://www.victorsgrill.com/',
],
    "Austronesian":['http://www.mypokehub.com/',
'https://leidpoke.com/',
'https://poke-it-up.business.site/',
'http://www.alohahawaiianbbqvb.com/',
'http://hawaiibbqva.com/',
'https://www.hawaiianbarbecue.com/location/chesapeake/',
],
    "African":['https://www.enatyerestaurant.com/',
'http://www.rahamarestautants.com/',
'https://www.facebook.com/AburiGardens13/',
'https://www.shebeen.com/',
'http://enatrestaurant.com/',
'http://www.enjera1.com/',
'http://www.fettoosh.com/',
'https://www.facebook.com/Sumahs-West-African-Restaurant-Carryout-167377406659052/',
'https://bellos-lounge.business.site/',
'http://www.appiooafricanbargrill.com/',
]
}
Roanoke_dict = {
    "Mexican": ['https://alejandrosmexicangrill.com/',
'https://www.facebook.com/tacosrojasmexican/',
'https://www.elrodeoroanoke.com/',
'https://la-casa-del-burrito-taco-shop.business.site/',
'https://tucostaqueria.com/menu',
'http://carlosbrazilian.com/',
'https://leonorerestaurant.com/',
'http://inkagrillperuviancuisine.com/',
],
    "Asian": ['http://www.benguisushi.com/',
'https://cafeasiava.com/#/',
'https://www.ikeskitchen.com/',
'https://www.redpalaceroanoke.com/',
'https://www.vietsubroanoke.com/',
'https://www.facebook.com/vinacaferoanoke/',
'http://redjasmine.net/',
],
    "Italian": ['https://www.reminiscafe.com/',
'https://www.bennysva.com/locations/benny-marconis/',
'http://www.fortunatoroanoke.com/',
'https://www.luigisvirginia.com/',
'http://www.franksatbrambleton.com/Home.htm',
],
    "Mediterranean/Middle East": ['https://www.petramedgrill.com/',
'https://cello-coffee-house-cafe.business.site/?utm_source=gmb&utm_medium=referral',
'http://www.paulsdowntown.com/',
'https://www.facebook.com/pages/category/Mediterranean-Restaurant/Bethlehem-Restaurant-Grocery-671666456276493/',
'http://www.cedarsofroanoke.com/',
'https://bamyan-afghan-cuisine.business.site/',
],
    "American": ['https://www.theroanokerrestaurant.com/',
'http://www.fork.rocks/fitm/',
'https://419-west.com/',
'http://thenewyorkerdeli.com/',
'https://www.facebook.com/thegreengoatrestaurant/',
'http://www.alexandersva.com/',
'https://www.odbb.com/roanoke/',
'https://bellacinos.com/',
'https://www.thegreat611.com/',
'https://wildflourattowers.com/',
],
    "Dessert/Cafe": ['http://sweetdonkeycoffee.com/',
'https://www.millmountaincoffee.com/',
'https://www.champloodesserts.com/#OIoLHl',
'https://bluecowicecream.com/',
'https://popsgrandin.com/',
'https://bubblecake.com/',
'http://littlegreenhive.com/',
'https://breadcraftbakery.com/',
'https://www.facebook.com/scrambledrnk',
],    "Modern": ['https://www.localrootsrestaurant.com/',
'https://www.wasenacitytaproom.com/',
'http://taazaroanoke.com/welcome/',
'https://petersseafood.com/',
'https://riverandrailrestaurant.com/',
'https://famoustoastery.com/',
],
    "European": [], #===========================NOTHING
    "Austronesian":[],#===========================NOTHING
    "African":[]#===========================NOTHING
}
Cville_dict = {
    "Mexican": ['http://www.eatdivide.com/',
'https://www.elpuertomexicancville.com/',
'https://www.guadalajaramexicanva.com/',
'http://eljaripeova.com/',
'https://www.sombreroscville.com/',
'https://thebebedero.com/',
'https://www.guajiros.net/',
'https://www.alcarbonchicken.com/Home',
],
    "Asian": ['https://www.facebook.com/PeterChangsCville/',
'https://www.monsoonsiamcville.com/',
'http://www.ten-sushi.com/',
'https://www.facebook.com/silkthaiva/',
'http://www.gotdumplingsandtea.com/',
'http://asianexpressva.com/',
'https://www.mingdynastyrestaurant.net/',
'https://tokyo-rose-restaurant.business.site/?utm_source=gmb&utm_medium=referral',
'https://www.taiwangardenva.com/',
'https://www.yelp.com/biz/cafe-88-charlottesville',
],
    "Italian": ['https://tavolavino.com/',
'http://www.lampopizza.com/',
'https://www.mangionesonmain.com/',
'https://www.vivacecville.com/',
'http://www.salscaffeitalia.com/',
'https://fellinisincville.com/',
],
    "Mediterranean/Middle East": ['https://www.sultankebabcville.com/',
'https://www.facebook.com/basilmedbistro',
'https://cava.com/',
'https://www.boxdkitchen.com/',
],
    "American": ['https://www.facebook.com/MelsSoulFoodCafe/',
'https://www.ivyinnrestaurant.com/',
'https://www.michietavern.com/',
'https://www.facebook.com/Mooses-by-the-Creek-313080362190930/timeline',
'http://woodgrillbuffetva.com/',
'https://www.thevirginiancville.com/',
'https://www.martinsgrill.com/',
'https://white-spot-hamburger-restaurant.business.site/?utm_source=gmb&utm_medium=referral',
'https://thelocal-cville.com/',
],
    "Dessert/Cafe": ['http://www.mariebette.com/#european-inspired',
'https://albemarlebakingco.com/',
'http://thepiechestcville.com/pies.php',
'http://chapsicecream.com/',
'http://www.hotcakes.biz/index.html',
'https://www.facebook.com/KirtsHomemadeIceCream/',
],
    "Modern": ['http://publicfo.com/',
'http://www.thefitzroycville.com/',
'https://www.meltingpot.com/charlottesville-va/',
'http://asadocville.com/',
'http://www.pokesushibowl.com/',
],
    "European": ['https://kardinalhall.com/',
'http://petitpoisrestaurant.com/index.html',
'https://www.brasseriesaison.com/',
'https://www.fleurierestaurant.com/',
'https://www.facebook.com/waterstreetcville/',
'http://www.tinwhistleirishpub.com/',
],
    "Austronesian":['https://hawaiianfoodcville.com/',
'https://www.thepieguyusa.com/',
],
    "African":['https://www.shebeen.com/']
}
Richmond_dict = {
    "Mexican": ['https://www.tiopablotacos.com/ ',
'https://www.mexicanrva.com/ ',
'http://mi-jalisco.com/ ',
'http://www.littlemexicova.com/ ',
'https://www.aycarambamexican.com/ ',
'http://labambarva.com/ ',
'http://www.casadelbarco.com/ ',
'http://ensuboca.com/ ',
'http://www.plazaazteca.com/ ',
'http://www.mijascantinarva.com/ ',
'http://www.wonggonzalez.com/ ',
'http://www.dontlookback.co/',
'http://laloscocina.com/',
'http://jalapenosmexicangrillrva.com/',
'http://www.amigosfamilyrestaurant.org/',
'http://mayarva.com/',
'http://www.mexico-restaurant.com/',
'http://www.tresmachos.com/',
'http://www.mexfoodrva.com/',
],
    "Asian": ['http://fatdragonrva.com/',
'http://www.wonggonzalez.com/',
'http://mekongisforbeerlovers.com/',
'http://www.pho1grill.com/',
'https://www.facebook.com/Sabairva',
'https://hirosushirichmond.com/',
'https://www.jiangschinese.com/',
'http://www.gingerthaitaste.com/',
'http://pekingdining.com/',
'https://www.senorganicsmallplate.com/',
'http://www.beijingongrove.com/',
'http://ilovestickyrice.com/',
'https://www.sptrva.com/',
'http://peterchangrestaurant.com/',
],
    "Italian": ['http://richmondgrapevine.com/',
'http://www.lagrottarva.com/',
'https://edossquidrva.com/',
'https://www.carinirestaurant.com/',
'https://www.ciaocaprirva.com/',
'https://pupatellarva.com/',
'http://bacchusrva.com/',
'https://casaitalianarestaurant.com/',],
    "Mediterranean/Middle East": ['https://www.nataliesrva.com/',
'https://www.2mfood.com/',
'https://cava.com/locations/short-pump-va',
'https://demisrva.com/',
'https://www.facebook.com/MesopotamiaDelicatessen',
],
    "American": ['http://balkanrichmond.com/',
'http://www.caferustika.com/',
'http://europeantasterva.com/',
'http://brennerpassrva.com/',
'http://www.bistrobobette.com/',
'http://www.lopossum.com/',
'http://maxsonbroad.com/',
'https://www.lescrepesrva.com/',
'http://www.cancanbrasserie.com/',
'https://www.perlysrichmond.com/',
'https://www.facebook.com/TheRedDoorRestaurant/',
'http://www.pennylanepub.com/',
'http://www.chezmaxva.com/',
'http://otoolesrestaurant.weebly.com/',
'http://www.lescrepescary.com/',
'http://www.sineirishpub.com/richmond',
],
    "Dessert/Cafe": ['https://garnettscafe.com/',
'http://www.whiskrva.com/',
'http://www.subrosabakery.com/',
'https://www.properpieco.com/',
'https://www.facebook.com/PlantZeroCafe/',
'https://www.821caferva.com/',
'http://www.shoredogcafe.com/',
'https://www.facebook.com/northendjuiceco/',
'https://stoplightgelatocafe.com/',
'http://crossroadsrva.com/',
],
    "Modern": ['http://www.stellasrichmond.com/',
'https://www.vmfa.museum/visit/dining/amuse-restaurant/',
'https://www.boathouseva.com/',
'http://brennerpassrva.com/ ',
'https://www.toastrva.com/',
'https://www.rroysters.com/',
'http://www.goatocado.com/ ',
'https://richmond-belvedere.firebirdsrestaurants.com/',
'https://ellwoodthompsons.com/',
'https://www.freshii.com/ca',
],
    "European": ['https://www.lunchorsupper.com/contact/',
'https://www.facebook.com/HogsHeadCafe/',
'http://mamajskitchen.com/',
'https://rooseveltrva.com/',
'https://www.croakersspot.com/',
'https://lucys2st.com/',
'https://www.bookbindersrichmond.com/',
'https://www.secretsandwichsociety.com/',
'https://www.dotsbackrichmond.com/',
'http://www.heritagerva.com/#',
'https://thehardshell.com/',
'http://www.kitchen64.com/',
'http://www.boulevardburgerandbrew.com/',
],
    "Austronesian":['http://www.kokonutgrill.com/',
'http://www.foodogrva.com/',
'http://hibachibox.com/',
'http://www.wingcommand.net/',
],
    "African":[ 'http://www.addisrva.com/',
'http://nilerva.com/',]
}

VB_dict = {
    "Mexican": [],
    "Asian": [],
    "Italian": [],
    "Mediterranean/Middle East": [],
    "American": [],
    "Dessert/Cafe": [],
    "Latin American": [],
    "Modern": [],
    "European": [],
    "Austronesian":[],
    "African":[]
}
BBurg_dict = {
    "Mexican": [],
    "Asian": [],
    "Italian": [],
    "Mediterranean/Middle East": [],
    "American": [],
    "Dessert/Cafe": [],
    "Latin American": [],
    "Modern": [],
    "European": [],
    "Austronesian":[],
    "African":[]
}


Main_dict = {
    "NOVA": NOVA_dict,
    "Roanoke": Roanoke_dict,
    "Charlottesville": Cville_dict,
    "Richmond": Richmond_dict,
    "Virginia_Beach": VB_dict,
    "Blacksburg": BBurg_dict
}
