import random

NOVA_dict = {
    "Mexican": ['https://www.guaposrestaurant.com/location/fair-lakes-guapos-restaurant/ ',
'http://www.elpasomexicanrestaurants.com/ ',
'http://www.coyotegrille.com/ ',
'http://www.anitascorp.com/ ',
'https://www.guajillomexican.com/ ',
'http://www.eltiogrill.com/'
'https://www.facebook.com/pampa.sazone',],
    "Asian": ['https://hotspotchantilly.wixsite.com/website',
'http://www.districtdumplingsfairfax.com/ ',
'http://www.kogiya.com/',
'http://oegadgib.com/',
'https://sistersthai.com/',
'https://www.facebook.com/pages/Viet-House-Restaurant/117697194916698',
'https://www.facebook.com/Hong-Kong-Pearl-Seafood-Restaurant-261076060610322/',
'https://www.grubhub.com/restaurant/blue-pearl-buffet-6820-commerce-st-springfield/2234586 '],
    "Italian": ['http://www.dolcevitaitaliankitchenandwinebar.com/',
'http://www.pazzopomodoro.com/vienna',
'http://www.trattoriavillagio.com/',
'http://osteriadaninova.com/ ',
'http://www.pomodoropastapizza.com/',
'https://www.altastradarestaurant.com/',
'http://www.cantinaditalia.com/',
],
    "Mediterranean/Middle East": ['https://anatolianbistro.com/',
'http://www.istanbulblue.net/',
'http://www.jerusalem-va.net/',
'http://mazadarrestaurantva.com/',
'http://www.mejanarestaurant.com/ ',
'http://www.flame-kabob.com/ ',
'https://m.facebook.com/bakudelicious/',
],
    "American": ['http://artiesva.com/',
'http://sweetwatertavern.pub/',
'http://21gab.com/',
'http://coastalflats.net/',
'https://americanprimeco.com/outdoor',
'http://mikesamerican.com/ ',
'https://dogfishalehouse.com/dfh-alehouse-fairfax.html',
'https://www.lostdogcafe.com/',
'https://chutzpahdeli.com/',
],
    "Dessert/Cafe": ['http://www.dulcecrepes.com/',
'http://dessertloungeva.site/',
'http://magnoliaofvienna.com/',
'https://www.grubhub.com/restaurant/manoa-bakery-cafe-7326-little-river-turnpike-annandale/2062340',
],
    "Modern": ['http://www.2941.com/ ',
'https://mapleaverestaurant.com/private-events/ ',
'http://bellissimorestaurant.com/',
'http://www.clarityvienna.com/',
],
    "European": ['http://m.bistrolhermitage.com/ ',
'http://theauldshebeenva.com/',
'https://braborestaurant.com/ ',
'http://www.laubergechezfrancois.com/ ',
'https://www.nandosperiperi.com/',
'http://www.ambarrestaurant.com/home-page-clarendon/ ',
'http://www.euro-bistro.com/ ',
'http://balkanrichmond.com/ ',
'http://europeantasterva.com/ ',
'http://www.laubergechezfrancois.com/ ',
'https://www.victorsgrill.com/',
],
    "Austronesian":['http://www.mypokehub.com/',
'https://leidpoke.com/',
'https://poke-it-up.business.site/',
'http://www.alohahawaiianbbqvb.com/',
'http://hawaiibbqva.com/',
'https://www.hawaiianbarbecue.com/location/chesapeake/',
],
    "African":['https://www.enatyerestaurant.com/',
'http://www.rahamarestautants.com/',
'https://www.facebook.com/AburiGardens13/',
'https://www.shebeen.com/',
'http://enatrestaurant.com/',
'http://www.enjera1.com/',
'http://www.fettoosh.com/',
'https://www.facebook.com/Sumahs-West-African-Restaurant-Carryout-167377406659052/',
'https://bellos-lounge.business.site/',
'http://www.appiooafricanbargrill.com/',
]
}
Roanoke_dict = {
    "Mexican": ['https://alejandrosmexicangrill.com/',
'https://www.facebook.com/tacosrojasmexican/',
'https://www.elrodeoroanoke.com/',
'https://la-casa-del-burrito-taco-shop.business.site/',
'https://tucostaqueria.com/menu',
'http://carlosbrazilian.com/',
'https://leonorerestaurant.com/',
'http://inkagrillperuviancuisine.com/',
],
    "Asian": ['http://www.benguisushi.com/',
'https://cafeasiava.com/#/',
'https://www.ikeskitchen.com/',
'https://www.redpalaceroanoke.com/',
'https://www.vietsubroanoke.com/',
'https://www.facebook.com/vinacaferoanoke/',
'http://redjasmine.net/',
],
    "Italian": ['https://www.reminiscafe.com/',
'https://www.bennysva.com/locations/benny-marconis/',
'http://www.fortunatoroanoke.com/',
'https://www.luigisvirginia.com/',
'http://www.franksatbrambleton.com/Home.htm',
],
    "Mediterranean/Middle East": ['https://www.petramedgrill.com/',
'https://cello-coffee-house-cafe.business.site/?utm_source=gmb&utm_medium=referral',
'http://www.paulsdowntown.com/',
'https://www.facebook.com/pages/category/Mediterranean-Restaurant/Bethlehem-Restaurant-Grocery-671666456276493/',
'http://www.cedarsofroanoke.com/',
'https://bamyan-afghan-cuisine.business.site/',
],
    "American": ['https://www.theroanokerrestaurant.com/',
'http://www.fork.rocks/fitm/',
'https://419-west.com/',
'http://thenewyorkerdeli.com/',
'https://www.facebook.com/thegreengoatrestaurant/',
'http://www.alexandersva.com/',
'https://www.odbb.com/roanoke/',
'https://bellacinos.com/',
'https://www.thegreat611.com/',
'https://wildflourattowers.com/',
],
    "Dessert/Cafe": ['http://sweetdonkeycoffee.com/',
'https://www.millmountaincoffee.com/',
'https://www.champloodesserts.com/#OIoLHl',
'https://bluecowicecream.com/',
'https://popsgrandin.com/',
'https://bubblecake.com/',
'http://littlegreenhive.com/',
'https://breadcraftbakery.com/',
'https://www.facebook.com/scrambledrnk',
],    "Modern": ['https://www.localrootsrestaurant.com/',
'https://www.wasenacitytaproom.com/',
'http://taazaroanoke.com/welcome/',
'https://petersseafood.com/',
'https://riverandrailrestaurant.com/',
'https://famoustoastery.com/',
],
    "European": [], #===========================NOTHING
    "Austronesian":[],#===========================NOTHING
    "African":[]#===========================NOTHING
}
Cville_dict = {
    "Mexican": ['http://www.eatdivide.com/',
'https://www.elpuertomexicancville.com/',
'https://www.guadalajaramexicanva.com/',
'http://eljaripeova.com/',
'https://www.sombreroscville.com/',
'https://thebebedero.com/',
'https://www.guajiros.net/',
'https://www.alcarbonchicken.com/Home',
],
    "Asian": ['https://www.facebook.com/PeterChangsCville/',
'https://www.monsoonsiamcville.com/',
'http://www.ten-sushi.com/',
'https://www.facebook.com/silkthaiva/',
'http://www.gotdumplingsandtea.com/',
'http://asianexpressva.com/',
'https://www.mingdynastyrestaurant.net/',
'https://tokyo-rose-restaurant.business.site/?utm_source=gmb&utm_medium=referral',
'https://www.taiwangardenva.com/',
'https://www.yelp.com/biz/cafe-88-charlottesville',
],
    "Italian": ['https://tavolavino.com/',
'http://www.lampopizza.com/',
'https://www.mangionesonmain.com/',
'https://www.vivacecville.com/',
'http://www.salscaffeitalia.com/',
'https://fellinisincville.com/',
],
    "Mediterranean/Middle East": ['https://www.sultankebabcville.com/',
'https://www.facebook.com/basilmedbistro',
'https://cava.com/',
'https://www.boxdkitchen.com/',
],
    "American": ['https://www.facebook.com/MelsSoulFoodCafe/',
'https://www.ivyinnrestaurant.com/',
'https://www.michietavern.com/',
'https://www.facebook.com/Mooses-by-the-Creek-313080362190930/timeline',
'http://woodgrillbuffetva.com/',
'https://www.thevirginiancville.com/',
'https://www.martinsgrill.com/',
'https://white-spot-hamburger-restaurant.business.site/?utm_source=gmb&utm_medium=referral',
'https://thelocal-cville.com/',
],
    "Dessert/Cafe": ['http://www.mariebette.com/#european-inspired',
'https://albemarlebakingco.com/',
'http://thepiechestcville.com/pies.php',
'http://chapsicecream.com/',
'http://www.hotcakes.biz/index.html',
'https://www.facebook.com/KirtsHomemadeIceCream/',
],
    "Modern": ['http://publicfo.com/',
'http://www.thefitzroycville.com/',
'https://www.meltingpot.com/charlottesville-va/',
'http://asadocville.com/',
'http://www.pokesushibowl.com/',
],
    "European": ['https://kardinalhall.com/',
'http://petitpoisrestaurant.com/index.html',
'https://www.brasseriesaison.com/',
'https://www.fleurierestaurant.com/',
'https://www.facebook.com/waterstreetcville/',
'http://www.tinwhistleirishpub.com/',
],
    "Austronesian":['https://hawaiianfoodcville.com/',
'https://www.thepieguyusa.com/',
],
    "African":['https://www.shebeen.com/']
}
Richmond_dict = {
    "Mexican": ['https://www.tiopablotacos.com/ ',
'https://www.mexicanrva.com/ ',
'http://mi-jalisco.com/ ',
'http://www.littlemexicova.com/ ',
'https://www.aycarambamexican.com/ ',
'http://labambarva.com/ ',
'http://www.casadelbarco.com/ ',
'http://ensuboca.com/ ',
'http://www.plazaazteca.com/ ',
'http://www.mijascantinarva.com/ ',
'http://www.wonggonzalez.com/ ',
'http://www.dontlookback.co/',
'http://laloscocina.com/',
'http://jalapenosmexicangrillrva.com/',
'http://www.amigosfamilyrestaurant.org/',
'http://mayarva.com/',
'http://www.mexico-restaurant.com/',
'http://www.tresmachos.com/',
'http://www.mexfoodrva.com/',
],
    "Asian": ['http://fatdragonrva.com/',
'http://www.wonggonzalez.com/',
'http://mekongisforbeerlovers.com/',
'http://www.pho1grill.com/',
'https://www.facebook.com/Sabairva',
'https://hirosushirichmond.com/',
'https://www.jiangschinese.com/',
'http://www.gingerthaitaste.com/',
'http://pekingdining.com/',
'https://www.senorganicsmallplate.com/',
'http://www.beijingongrove.com/',
'http://ilovestickyrice.com/',
'https://www.sptrva.com/',
'http://peterchangrestaurant.com/',
],
    "Italian": ['http://richmondgrapevine.com/',
'http://www.lagrottarva.com/',
'https://edossquidrva.com/',
'https://www.carinirestaurant.com/',
'https://www.ciaocaprirva.com/',
'https://pupatellarva.com/',
'http://bacchusrva.com/',
'https://casaitalianarestaurant.com/',
],
    "Mediterranean/Middle East": ['https://www.nataliesrva.com/',
'https://www.2mfood.com/',
'https://cava.com/locations/short-pump-va',
'https://demisrva.com/',
'https://www.facebook.com/MesopotamiaDelicatessen',
],
    "American": ['https://www.lunchorsupper.com/contact/',
'https://www.facebook.com/HogsHeadCafe/',
'http://mamajskitchen.com/',
'https://rooseveltrva.com/',
'https://www.croakersspot.com/',
'https://lucys2st.com/',
'https://www.bookbindersrichmond.com/',
'https://www.secretsandwichsociety.com/',
'https://www.dotsbackrichmond.com/',
'http://www.heritagerva.com/#',
'https://thehardshell.com/',
'http://www.kitchen64.com/',
'http://www.boulevardburgerandbrew.com/',
],
    "Dessert/Cafe": ['https://garnettscafe.com/',
'http://www.whiskrva.com/',
'http://www.subrosabakery.com/',
'https://www.properpieco.com/',
'https://www.facebook.com/PlantZeroCafe/',
'https://www.821caferva.com/',
'http://www.shoredogcafe.com/',
'https://www.facebook.com/northendjuiceco/',
'https://stoplightgelatocafe.com/',
'http://crossroadsrva.com/',
],
    "Modern": ['http://www.stellasrichmond.com/',
'https://www.vmfa.museum/visit/dining/amuse-restaurant/',
'https://www.boathouseva.com/',
'http://brennerpassrva.com/ ',
'https://www.toastrva.com/',
'https://www.rroysters.com/',
'http://www.goatocado.com/ ',
'https://richmond-belvedere.firebirdsrestaurants.com/',
'https://ellwoodthompsons.com/',
'https://www.freshii.com/ca',
],
    "European": ['http://balkanrichmond.com/',
'http://www.caferustika.com/',
'http://europeantasterva.com/',
'http://brennerpassrva.com/',
'http://www.bistrobobette.com/',
'http://www.lopossum.com/',
'http://maxsonbroad.com/',
'https://www.lescrepesrva.com/',
'http://www.cancanbrasserie.com/',
'https://www.perlysrichmond.com/',
'https://www.facebook.com/TheRedDoorRestaurant/',
'http://www.pennylanepub.com/',
'http://www.chezmaxva.com/',
'http://otoolesrestaurant.weebly.com/',
'http://www.lescrepescary.com/',
'http://www.sineirishpub.com/richmond',
],
    "Austronesian":['http://www.kokonutgrill.com/',
'http://www.foodogrva.com/',
'http://hibachibox.com/',
'http://www.wingcommand.net/',
],
    "African":[ 'http://www.addisrva.com/',
'http://nilerva.com/',
]
}

VB_dict = {
    "Mexican": ['http://www.sidestreetcantina.com/',
'https://www.laspalmasmexicanvb.com/',
'https://www.granrodeomexicangrill.com/',
'https://plazaazteca.com/',
'https://www.facebook.com/El-Patron-Mexican-Restaurant-117574338268473/',
'http://micasitamexican.com/',
],
    "Asian": ['http://forbiddenpalacevirginiabeachva.com/',
'http://www.imperialpalacevb.com/',
'http://www.goldencity3.com/',
'http://www.peterchangvb.com/',
'http://www.jadevillavb.com/',
'https://www.pfchangs.com/locations/us/va/virginia-beach/4551-virginia-beach-blvd/9909-virginia-beach.html?utm_source=YextMain&utm_medium=Directory&y_source=1_NTI2NTQzMy03MTUtbG9jYXRpb24ud2Vic2l0ZQ%3D%3D',
'http://www.shunxingvabeach.com/',
'https://stirfryvb.com/',
'http://www.judyssichuancuisine.com/',
'http://www.virginiabeachjadegarden.com/',
'https://misako-asian-cuisine.business.site/',
'http://www.kinghuachinese.com/',
'http://www.fuhingva88.com/ ',
'https://sapporoeastbeach.com/ ',
],
    "Italian": ['https://wheninromevb.com/',
'https://www.manninositalianbistro.com/home',
'https://planetpizzavb.com/',
'https://www.19thstreetitalianbistrova.com/',
'http://www.aldosvb.com/',
'https://reginellas.com/',
'http://www.ilgiardino.com/',
'http://www.planetpizzavb.com/',
'https://www.bravoitalian.com/?y_source=1_MTU5OTgwNDQtNzY5LWxvY2F0aW9uLndlYnNpdGU%3D',
],
    "Mediterranean/Middle East": ['https://baladicafe.com/',
'https://m.facebook.com/Mazarikebab/?ref=py_c',
'http://www.mediterraneancuisinevb.com/',
'https://www.azarfoods.com/menu-azars-at-hilltop/',
'https://www.facebook.com/papasgreek1/',
'https://www.jennascafe.com/',
],
    "American": ['http://parklanetavern.com/',
'http://hairofthedogva.com/',
'http://1608crafthouse.com/',
'http://eatbistro.net/',
'http://www.repealvb.com/',
'https://baylocalvb.com/',
'http://www.58deli.com/',
'https://www.beebiscuit.com/',
],
    "Dessert/Cafe": ['https://rigolettoitalianbakeryvb.com/',
'https://sugarplumbakery.org/',
'https://www.facebook.com/maysparlor/',
'http://www.confetticafe.com/',
'https://www.facebook.com/Iscreamicecreamvb',
'https://bluecowicecream.com/',
'https://www.facebook.com/acookiesandwich/',
'https://www.facebook.com/Rolling-Bowl-Stir-Fry-Ice-Cream-413304615707734/',
],
    "Modern": ['https://www.yianniswine.com/',
'https://myvegansweettooth.com/',
'https://www.facebook.com/mosaiccafee/',
'https://www.19thstreetitalianbistrova.com/',
'https://www.watermans.com/',
'https://www.tautogs.com/',
'https://www.thewhiskeykitchen.com/',
],
    "European": ['http://www.leyacawilliamsburg.com/',
'https://www.facebook.com/pages/category/Restaurant/The-Bier-Garden-Festhaus-345555229591847/',
'https://murphyspubvb.com/',
'https://keagansvb.com/',
'https://www.facebook.com/The-Highlander-A-Fine-British-Eatery-191800547530261/',
'https://www.jimmydagreeks.com/',
],
    "Austronesian":['http://www.susanskitchenette.com/',
'https://glorysbakery.wpcomstaging.com/',
'https://www.facebook.com/onlyatrenees/',
'http://lumpiavb.com/',
'https://www.penangtownmalaysian.com/',
'https://www.ihawihaw.co/',
],
    "African":['https://www.mesobcafe.com/',
'http://www.lillyscorner.net/ ',
'http://www.yendidirestaurant.com/',
'https://lynnz-african-cuisine.business.site/?utm_source=gmb&utm_medium=referral',
'http://www.montegogrill.com/',
'http://www.dericanchefva.com/',
]
}
BBurg_dict = {
    "Mexican": ['http://www.elmariachiblacksburg.com/',
'https://elrodeonorthmain.com/',
'http://www.cabofishtaco.com/',
'https://www.moes.com/find-a-moes/virginia/blacksburg/575?utm_source=google&utm_medium=organic&utm_campaign=localmaps',
'https://www.facebook.com/elgranrode0/?rf=166080700115198',
'https://tacos-el-tio-mexican-restaurant.business.site/',
],
    "Asian": ['http://spicityva.com/',
'https://www.happywokblacksburg.com/',
'https://www.hunankingva.com/',
'http://www.cafe-mekong.com/',
'https://www.sakehouserestaurant.com/',
'https://www.blacksburgcafedebangkok.com/',
'https://www.hunankingva.com/',
],
    "Italian": ['https://www.orderitalianospizzamenu.com/',
'http://www.avellinosrestaurant.com/',
'http://zeppolis.com/',
'http://www.ceritanos.com/',
'https://www.orderitalianospizzamenu.com/',
],
    "Mediterranean/Middle East": ['http://www.mezeh.com/',
'http://www.luciemonroesblacksburg.com/',
'https://zoeskitchen.com/locations/store/va/blacksburg',
'http://www.eatsouvlaki.com/',
'https://www.the-cellar.com/',
'http://www.cedarsofroanoke.com/',
'http://petramedgrill.com/',
'http://facebook.com/TheGreeksrestaurant',
],
    "American": ['http://www.hokiehouse.com/',
'https://www.theblackhenrestaurant.com/',
'http://www.622north.com/menus/',
'http://www.leftysgrille.com/',
'https://theblacksburgtavern.com/',
'https://www.innatvirginiatech.com/blacksburg_restaurants/prestons/',
'https://the-cellar.com/',
],
    "Dessert/Cafe": ['https://www.carolleedonuts.com/',
'https://www.sugarmagnoliaburg.com/',
'https://www.chocolatespike.com/',
'https://www.odbb.com/',
'https://www.nextdoorbakeshop.com/',
],
    "Latin American": [],
    "Modern": ['https://gilliesrestaurant.com/ ',
'http://www.greensgrillsushibar.com/',
],
    "European": [],#========================NOTHING
    "Austronesian":['https://easterndivide.com/',
],
    "African":[] #========================NOTHING
}


Main_dict = {
    "NOVA": NOVA_dict,
    "Roanoke": Roanoke_dict,
    "Charlottesville": Cville_dict,
    "Richmond": Richmond_dict,
    "Virginia_Beach": VB_dict,
    "Blacksburg": BBurg_dict
}

#print(Main_dict["Blacksburg"]["Dessert/Cafe"][0])

def get_restaurant(City,Cuisine,Main_dict,top_3=False):
    if top_3 == True:
        sz = len(Main_dict[City][Cuisine])
        if sz >= 3:
            rlist = random.sample(range(0,sz),3)
            output = []
            for i in range(0,len(rlist)):
                output.append(Main_dict[City][Cuisine][rlist[i]])
            return output
    else:
        return Main_dict[City][Cuisine]

# print(get_restaurant("Richmond","Italian",Main_dict,True))